echo "Run integration"
echo "Our new feature can show a magic number"
echo "You should switch to new branches with `git checkout -b <branch_name>"
echo "Git is really awesome and it's distributed"
echo "This means that it's very lightweight and scales"
